### ISSUE TITLE
Shutdown or ill shut U down

### ISSUE THREAD

**Issue by Reksa4real** [Nicks-Alt/loggingSuite#1]
How is there a virus in the program and Avast done quarantined it and removed it from my desktop? Then on top of that why is it that when the program is obviously gone and out my control, the shutdown timer is still running. So I can use my PC for 15 minutes until the program shuts it down. This prob why Megan left u

**Comment by nicksuperiorservers** [comment]
Get outta my repo u fucking bitch

**Comment by Reksa4real** [comment]
So the virus issue happens when you close the logging suite but the time on the reminder time has not reached yet. So with the program shut down and the timer running in the background avast will think something is trying to shut down the computer without a windowed program open.

**Comment by Nicks-Alt** [comment]
![chrome_fxZBdmhCTd](https://user-images.githubusercontent.com/43933668/69435803-3fd75000-0d0e-11ea-92da-8e6b51c514cc.png)
